### ISSUE TITLE
Black Screen / No video

### ISSUE THREAD

**Issue by Paullus1** [moonlight-stream/moonlight-ios#237]
When connecting from an IOS device there is no video. Only a black screen with onscreen controls. When connecting with an Android tv the video works. I already tried the actions mentioned under the "No video" section. (disable anti virus, rebooting and reinstalling geforce expierence). Also tried a "Clean Install" of the latest drivers.

-Windows 10 Pro, GTX 970. Latest drivers

**Comment by g1084164986** [comment]
So do I, I have this issue too.

**Comment by beardogdog** [comment]
+1 same issue, i have the 970 aswell

**Comment by MichaelMKenny** [comment]
+1

**Comment by mikekucek** [comment]
I have the same issue running iOS 10.

**Comment by MichaelMKenny** [comment]
Can confirm it's an iOS 10 thing. I have a 9.3.3 device that's working fine.

**Comment by cgutman** [comment]
I will see if I can reproduce the issue in an iOS 10 emulator. What devices are you seeing this issue on?

**Comment by Paullus1** [comment]
- iPhone 6 iOS 10
- iPad mini 2 iOS 10
 But my iPad mini 1 iOS 9.x experienced this problem as well afterwards...

**Comment by mikekucek** [comment]
iPhone 6s and iPad Pro 12.9, both on iOS 10.
Windows 10 (no insider builds)
GFE v2.11.4.0
GTX 1070 v368.81

Just to clarify, the game is running on my PC fine. The devices have sound and working on-screen controls, but no video.

**Comment by cgutman** [comment]
I have found the issue, and it looks to be a bug (or behavior change in iOS 10). I have filed a bug on the iOS bug tracker and have developed a workaround that I can use if they can't/won't fix the issue for a while.

**Comment by cgutman** [comment]
The workaround is implemented in cc6211a58f5e6d6fa254030307154bdaf066eb27 but I'm going to wait for Apple's response to see whether they intend to fix this bug or whether it is intended behavior.

**Comment by cgutman** [comment]
Apple is aware of the issue and it will hopefully be fixed in a future build (if not already). Can someone confirm that the latest iOS 10 beta is still affected?

**Comment by Paullus1** [comment]
Moonlight works GREAT with the latest ios 10 public beta 5 on my iPhone 6
and iPad mini 2.

Thank you all!

**Comment by andy1717** [comment]
Have the issue with iPad 4th gen.
IOS: 9.3.5

**Comment by jaydeelive01** [comment]
I also have the same issue on my iPad using iOS 9.3 and on my MacBook pro.

When I use my macbook, if I uncheck the fullscreen mode, I get video and controls. But I cannot do that on my iOS device...

**Comment by JohnJDDoe** [comment]
Have this issue. I tried everything on the FAQ and it still not work. I get audio, but no video.

iPad Air 2 iOS 10.0.2 and iPhone 5S iOS 10.0.2
Windows 10, GTX 980ti, Geforce Experience 3.0.7.34, Geforce Driver 373.06

**Comment by cgutman** [comment]
This is a known issue with GFE 3.0.7. We have submitted a Moonlight update to Apple to fix it and requested an expedited review.

**Comment by cgutman** [comment]
@JohnJDDoe it looks like the update is live now

**Comment by JohnJDDoe** [comment]
@cgutman I'm going to try it right now

**Comment by javis** [comment]
Problem also happening on FireTV client.
Geforce Experience version = 3.0.7

**Comment by cgutman** [comment]
@javis You still get the black screen on your FireTV? Please check what version of Moonlight is installed and whether an update is pending for it. The fixed v4.7.2 is live on the Amazon store and has been for days now.

**Comment by javis** [comment]
@cgutman I started to experience the problem after the update of Oct 5.

**Comment by cgutman** [comment]
@javis Yes, that was a GeForce Experience update that requires a new version of Moonlight to work. I need to know if you're running the updated Moonlight version on your Fire TV.

**Comment by javis** [comment]
@cgutman I think so, current Moonlight version installed 4.7.2, no updates available

**Comment by cgutman** [comment]
@javis what model of Fire TV do you have? Can you also check that you have a display connected to your PC and turned on?

**Comment by javis** [comment]
@cgutman First generation of FireTV. I do have a display connected to my pc. and it's always turned on

**Comment by javis** [comment]
Hi Guys any news on the FireTV issue? 
Thanks!

**Comment by cgutman** [comment]
@javis I tried it on my Fire TV and saw the same bug. It turns out that Amazon isn't pushing the update to Fire TVs correctly it seems. Even though the app page said it was 4.7.2, it was actually running 4.7 (even though it claimed to be up to date). Uninstalling and reinstalling the app fixed the issue.

**Comment by javis** [comment]
@cgutman  Ok!  I will try that, thanks!

**Comment by javis** [comment]
@cgutman Thanks! it works now :D

**Comment by davewolax** [comment]
I have this problem too. Running iOS 10.2 on an iPhone 7. how to fix this?

**Comment by cgutman** [comment]
You'll have to wait until Apple approves the new build.

**Comment by davewolax** [comment]
So it is fixed in the latest build? how long does it take for it to be approved on AppStore?

**Comment by cgutman** [comment]
Build 1.1.4 should be live in the store now with the fix for GFE 3.2
