### ISSUE TITLE
Moonlight only supports adding PCs on local network on IOS

### ISSUE THREAD

**Issue by AlexwannaCode** [moonlight-stream/moonlight-ios#417]
Is it the IOS limitation?

**Comment by cgutman** [comment]
Apple's [App Store Review Guideline 4.2.7a](https://developer.apple.com/app-store/review/guidelines/#design) states:
> The app must only connect to a user-owned host device that is a personal computer or dedicated game console owned by the user, and both the host device and client must be connected on a local and LAN-based network. 

Therefore, Moonlight does not allow you to add PCs that aren't on your local network anymore. This was a hard requirement by Apple's App Store Review team.

If you _have_ to add your PC remotely, you may have success using a VPN like [ZeroTier](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#zerotier) which looks like a LAN connection to other apps.

**Comment by abusse** [comment]
Wouldn't it be possible to make/release a dedicated version that only allows desktop access like Shadow reverted to after the hassle with the quoted rules or restrict internet hosts to that functionality?

**Comment by cgutman** [comment]
Nope, I proposed this exact thing to them and they rejected it.

**Comment by abusse** [comment]
The first or the latter one (or both)? Was there something different that you proposed compared to how Shadow is doing it with their revised tvOS/iOS app?

**Comment by cgutman** [comment]
Both. My proposed solution was essentially to act like a remote desktop app, similar to Microsoft Remote Desktop.

I asked about other game streaming apps that do the same thing, and they told me they are investigating those too for possible policy violations.

**Comment by abusse** [comment]
May I ask about the timeline when you had this "discussion" with Apple? I'm asking because the Shadow app was kicked from the App Store for exactly that reason, but then re-allowed after removing the direct game access and reverting to remote desktop only. Their argument sounds like you had asked before that happened? Maybe it's worth another try with this precedent? Or they have additional information what is necessary to be allowed into the App Store like the Shadow app was.

**Comment by cgutman** [comment]
The talks were after Shadow was re-approved.

I'm not going to be contesting this with Apple again anytime soon. Due to the review proceedings, I was left unable to ship any new Moonlight builds (even bugfixes) for over 3 months while this whole situation played out. If Nvidia had released a GFE update that required a Moonlight update, iOS users would have been unable to use the app anymore. It's simply not worth the risk to contest it.

**Comment by sean256** [comment]
How easy is it to disable the block should one build from source?

**Comment by abusse** [comment]
It is pretty easy. There is just one definition of `ENABLE_APP_STORE_RESTRICTIONS` that enforces the App Store restrictions. Just make sure that you don't have set it during build and all App Store restrictions should be disabled (cf [this](https://github.com/moonlight-stream/moonlight-ios/blob/a66d6eb11b4492ec4dc247b55b6f4b6dbd3db36f/Moonlight.xcodeproj/project.pbxproj#L1283)).

**Comment by witchcraftsman** [comment]
> If you _have_ to add your PC remotely, you may have success using a VPN like [ZeroTier](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#zerotier) which looks like a LAN connection to other apps.

Since ZeroTier can't be used on tvos, what are the options other then source building (guess it'd also require apple dev account to deploy to the box, atm having none) ?

**Comment by redlinejoes** [comment]
> > If you _have_ to add your PC remotely, you may have success using a VPN like [ZeroTier](https://github.com/moonlight-stream/moonlight-docs/wiki/Setup-Guide#zerotier) which looks like a LAN connection to other apps.
> 
> Since ZeroTier can't be used on tvos, what are the options other then source building (guess it'd also require apple dev account to deploy to the box, atm having none) ?
> EDIT: I guess joining separate LANs with VPN would work but encryption overhead etc would kill its purpose

This guy gets it. Although you typically want encryption, there is unnecessary overhead here with regards to streaming service providers infrastructure services. I’m planning to build from source and remove the limitation myself. I’m not interested in paying Apple the $99 annually at this time though. So I will go another step further and build a CI/CD server to push the build every week or as needed. If you’re interested in helping out, or learning from my experience, don’t hesitate to reach out. I’m so appreciative of moonlight being open source and these companies are all seemingly trying to stifle remote streaming service providers offerings. It wreaks off anti competitive action.

**Comment by Heath123** [comment]
Please can someone host builds with this enabled? People can sideload them with AltStore or a jailbreak

**Comment by boazvdwansem** [comment]
> Please can someone host builds with this enabled? People can sideload them with AltStore or a jailbreak

Please?

**Comment by Heath123** [comment]
If no one else is going to maybe I could but I’m not sure if I need a Mac OS VM to build it (I don’t have a Mac)

**Comment by Heath123** [comment]
I'm installing Mac OS in a VM now, if I get it built I'll upload an IPA

**Comment by Heath123** [comment]
![image](https://user-images.githubusercontent.com/13787163/128199049-ce4d3dbc-5f67-490f-acc4-ee792e0ce13a.png)

**Comment by boazvdwansem** [comment]
> I'm installing Mac OS in a VM now, if I get it built I'll upload an IPA

Had any success yet? I'm currently installing Mac OS in a VM as well, will post if I have anything to share.

**Comment by redlinejoes** [comment]
I have actual macOS physical systems but in order for me to do this, I would have to pay the $99 Apple Developer fee or be required to rebuild it every 7(days). That is the requirement if you do not jailbreak your iOS device which I had no intention of doing. This is really a headache and because I can use other apps like Splashtop, I've just stopped using Moonlight. I expected more "push back" by Moonlight senior dev towards Apple's anticompetitive tactics. How are you guys getting around the Apple developer costs? Or do you plan to use CI/CD to just keep pushing a new version every 7, or whatever number, of days?

**Comment by redlinejoes** [comment]
> If no one else is going to maybe I could but I’m not sure if I need a Mac OS VM to build it (I don’t have a Mac)

As far as I know, it requires Xcode and TestFlight on macOS, so you do need an Apple system and you need an Apple Developer account. I've been an Apple Developer before so I'm familiar with the processes and procedures, but I'm open to hearing if there are other ways this can be done. I just don't want to jailbreak my device.

**Comment by boazvdwansem** [comment]
> > If no one else is going to maybe I could but I’m not sure if I need a Mac OS VM to build it (I don’t have a Mac)
> 
> As far as I know, it requires Xcode and TestFlight on macOS, so you do need an Apple system and you need an Apple Developer account. I've been an Apple Developer before so I'm familiar with the processes and procedures, but I'm open to hearing if there are other ways this can be done. I just don't want to jailbreak my device.

I'm using a jailbreak for signing, I don't think there is a way around the developer account fee

**Comment by boazvdwansem** [comment]
![Schermafbeelding 2021-08-05 021630](https://user-images.githubusercontent.com/55191679/128271815-c9e1b213-5845-4eea-a013-b676af8f98da.png)
Does anyone know how to fix this?

**Comment by don17sch** [comment]
https://drive.google.com/drive/folders/13ebjY2qSVJebr2hLjTXTHkD981bl0Tb1?usp=sharing


Here you go. ipa built with the app store restriction removed

**Comment by boazvdwansem** [comment]
> https://drive.google.com/drive/folders/13ebjY2qSVJebr2hLjTXTHkD981bl0Tb1?usp=sharing
> 
> Here you go. ipa built with the app store restriction removed

Thank you very much

**Comment by boazvdwansem** [comment]
Well it seems like even without the restriction on it won't work :/

**Comment by redlinejoes** [comment]
> Well it seems like even without the restriction on it won't work :/

I was afraid of that. Maybe the Moonlight discord would be kind enough to give some advice. Have you tried there?

**Comment by boazvdwansem** [comment]
> > Well it seems like even without the restriction on it won't work :/
> 
> I was afraid of that. Maybe the Moonlight discord would be kind enough to give some advice. Have you tried there?

How did you get it to build tho? By looking at the commits I found that https://github.com/moonlight-stream/moonlight-ios/commit/dbab07838d29388ac9e547905e00836d54c6dd17 Is the one where it’s introduced, by setting these values to false it should work.

**Comment by don17sch** [comment]
> 
> 
> > https://drive.google.com/drive/folders/13ebjY2qSVJebr2hLjTXTHkD981bl0Tb1?usp=sharing
> > Here you go. ipa built with the app store restriction removed
> 
> Thank you very much. Do you happen to know why I got that error above?

You needed to run this command in terminal. 'git submodule update --init --recursive' 
you did not have the core part of moonlight added yet

**Comment by don17sch** [comment]
> 
> 
> Well it seems like even without the restriction on it won't work :/

I tried at least. sorry it did not work for you

**Comment by redlinejoes** [comment]
> > Well it seems like even without the restriction on it won't work :/
> 
> I tried at least. sorry it did not work for you

But did it work for you?

**Comment by don17sch** [comment]
> 
> 
> > > Well it seems like even without the restriction on it won't work :/
> > 
> > 
> > I tried at least. sorry it did not work for you
> 
> But did it work for you?

I just built it with the flag for app store restrictions turned off. I personally do not know how to connect to my pc remotely

**Comment by boazvdwansem** [comment]
It seems like the issue is coming from a unreachable file: http://ip-here:47989/serverinfo, I’ve tried forwarding already but it still isn’t reachable, only through my local network.

**Comment by don17sch** [comment]
> 
> 
> It seems like the issue is coming from a unreachable file: http://ip-here:47989/serverinfo, I’ve tried forwarding already but it still isn’t reachable, only through my local network. Other than that, removing the flag actually seems to work.

did you install this tool to check that your pc can host over the internet?

**Comment by boazvdwansem** [comment]
> > It seems like the issue is coming from a unreachable file: http://ip-here:47989/serverinfo, I’ve tried forwarding already but it still isn’t reachable, only through my local network. Other than that, removing the flag actually seems to work.
> 
> did you install this tool to check that your pc can host over the internet?
> https://github.com/moonlight-stream/Internet-Hosting-Tool

Yep, canyouseeme.org even says the port is opened but yet I can only reach locally. I’ve also tried using xampp to host the serverinfo file but seems like it needs to be updated after connecting so that won’t work either.

**Comment by don17sch** [comment]
> 
> 
> > > It seems like the issue is coming from a unreachable file: http://ip-here:47989/serverinfo, I’ve tried forwarding already but it still isn’t reachable, only through my local network. Other than that, removing the flag actually seems to work.
> > 
> > 
> > did you install this tool to check that your pc can host over the internet?
> > https://github.com/moonlight-stream/Internet-Hosting-Tool
> 
> Yep, canyouseeme.org even says the port is opened but yet I can only reach locally. I’ve also tried using xampp to host the serverinfo file but seems like it needs to be updated after connecting so that won’t work either.

this is what you should see when the page connects

<?xml version="1.0" encoding="UTF-16"?><root protocol_version="0.1" query="serverinfo" status_code="200" status_message="OK"><AuthenticationType>1</AuthenticationType><ConnectionState></ConnectionState><CurrentClient>0</CurrentClient><GfeVersion>3.23.0.74</GfeVersion><GsVersion>gs_04_31_29971906</GsVersion><HttpsPort>47984</HttpsPort><LocalIP>10.0.0.122</LocalIP><LocalIPs><Address>10.0.0.122</Address></LocalIPs><LocalIPs><Address>172.24.96.1</Address></LocalIPs><LoginState>2</LoginState><MaxLumaPixelsH264>1721324928</MaxLumaPixelsH264><MaxLumaPixelsHEVC>1869449984</MaxLumaPixelsHEVC><Mode>0</Mode><PairStatus>0</PairStatus><ServerCapability>3895</ServerCapability><ServerCodecModeSupport>3843</ServerCodecModeSupport><ServerColorSpaceSupport>2</ServerColorSpaceSupport><SupportedDisplayMode><DisplayMode><Height>2160</Height><RefreshRate>60</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>2160</Height><RefreshRate>30</RefreshRate><Width>3840</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>60</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>1080</Height><RefreshRate>30</RefreshRate><Width>1920</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>60</RefreshRate><Width>1280</Width></DisplayMode><DisplayMode><Height>720</Height><RefreshRate>30</RefreshRate><Width>1280</Width></DisplayMode></SupportedDisplayMode><accountId>92D7EF683905590215BBFF85D3E49F14FFF70F62DD6337485293FC40DA6A07F3</accountId><appversion>7.1.431.0</appversion><currentgame>0</currentgame><gamelistid>f1528daf6a1665d3cfccd43532cae37b</gamelistid><gputype>NVIDIA GeForce RTX 2070 SUPER</gputype><hostname>DONALDS-DESKTOP</hostname><mac>58:96:1D:5C:5B:B6</mac><numofapps>0</numofapps><resyncSuccessful>0</resyncSuccessful><state>MJOLNIR_STATE_SERVER_AVAILABLE</state><uniqueid>10ae00be-d6db-4c9e-bea5-ef7725e4dcfd</uniqueid></root>

**Comment by cgutman** [comment]
Just to confirm, you're just typing your IP address in the Add PC field, not a URL or anything like that, correct?

Some routers don't allow you to access services via the WAN/Internet address of your router while you're on the LAN (called NAT hairpinning). Make sure you're not connected to the same network as your PC and router when you are trying to add the PC using the WAN IP address.

**Comment by boazvdwansem** [comment]
> Just to confirm, you're just typing your IP address in the Add PC field, not a URL or anything like that, correct?
> 
> Some routers don't allow you to access services via the WAN/Internet address of your router while you're on the LAN (called NAT hairpinning). Make sure you're **not** connected to the same network as your PC and router when you are trying to add the PC using the WAN IP address.

Thank you so much it’s working now, it was because I was connecting from the same IP address.

**Comment by boazvdwansem** [comment]
> Just to confirm, you're just typing your IP address in the Add PC field, not a URL or anything like that, correct?
> 
> Some routers don't allow you to access services via the WAN/Internet address of your router while you're on the LAN (called NAT hairpinning). Make sure you're **not** connected to the same network as your PC and router when you are trying to add the PC using the WAN IP address.

Am I allowed to redistribute the IPA online? @cgutman

**Comment by don17sch** [comment]
should I have asked for permission before posting the IPA @cgutman  if so I am sorry for not doing so

**Comment by cgutman** [comment]
Yes, you're allowed to redistribute binaries from GPLv3 licensed projects as long as you link back to the source code.

**Comment by don17sch** [comment]
> 
> 
> > Just to confirm, you're just typing your IP address in the Add PC field, not a URL or anything like that, correct?
> > Some routers don't allow you to access services via the WAN/Internet address of your router while you're on the LAN (called NAT hairpinning). Make sure you're **not** connected to the same network as your PC and router when you are trying to add the PC using the WAN IP address.
> 
> Am I allowed to redistribute the IPA online? @cgutman

feel free to message me when you need me to build new ipa files.

**Comment by boazvdwansem** [comment]
I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested

**Comment by redlinejoes** [comment]
> I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested

Just to confirm. You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work? 
In order to connect to your WAN IP, you need to be on the Internet (WAN). 

When going to your URL, I do not see where there is a moonlight IPA listed. 

Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation?

**Comment by don17sch** [comment]
> 
> 
> > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> 
> Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> In order to connect to your WAN IP, you need to be on the Internet (WAN).
> 
> When going to your URL, I do not see where there is a moonlight IPA listed.
> 
> Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?

My IPA was built with the $99 a year license already attatched

**Comment by redlinejoes** [comment]
> > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > 
> > 
> > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > When going to your URL, I do not see where there is a moonlight IPA listed.
> > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> 
> My IPA was built with the $99 a year license already attached

Would you be interested in forking and adding it to your Github? I believe it would be a popular addition to your repo if you choose to do that. I intended to do this same thing myself, but you guys beat me to it. Whatever you decide, thanks so much for the support from all of you that have helped. I'm very grateful to see others who feel the same way I do about this restriction from Apple. I feel really bad for Cameron who got put in this position by Apple.

**Comment by boazvdwansem** [comment]
> > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> 
> Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> In order to connect to your WAN IP, you need to be on the Internet (WAN).
> 
> When going to your URL, I do not see where there is a moonlight IPA listed.
> 
> Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?

I tried connecting inside my LAN to WAN, that was the issue. The URL I posted is to add in a apt package manager if jailbroken (Cydia for example). The only way around the 7 days limitation that I know of is AltStore/ jailbreak. I have uploaded an IPA I built myself to: https://github.com/boazvdwansem/ios-repo/tree/main/ipas, but it should be t almost identical as the one @don17sch posted

**Comment by redlinejoes** [comment]
> > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > 
> > 
> > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > When going to your URL, I do not see where there is a moonlight IPA listed.
> > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> 
> I tried connecting inside my LAN to WAN, that was the issue. The URL I posted is to add in a apt package manager if jailbroken (Cydia for example). The only way around the 7 days limitation that I know of is AltStore/ jailbreak. I have uploaded an IPA I built myself to: https://github.com/boazvdwansem/ios-repo/tree/main/ipas, but it should be t almost identical as the one @don17sch posted

Awesome, thanks for clarifying, and thanks for all the help. You guys are awesome.

**Comment by don17sch** [comment]
> 
> 
> > > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > > 
> > > 
> > > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > > When going to your URL, I do not see where there is a moonlight IPA listed.
> > > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> > 
> > 
> > My IPA was built with the $99 a year license already attached
> 
> Would you be interested in forking and adding it to your Github? I believe it would be a popular addition to your repo if you choose to do that. I intended to do this same thing myself, but you guys beat me to it. Whatever you decide, thanks so much for the support from all of you that have helped. I'm very grateful to see others who feel the same way I do about this restriction from Apple. I feel really bad for Cameron who got put in this position by Apple.

forking this does not make sense as all I did was turn off a flag in build settings. also if I fork it you will still need to sign it yourself when you build it. I only signed those specific IPA files

**Comment by redlinejoes** [comment]
> > > > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > > > 
> > > > 
> > > > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > > > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > > > When going to your URL, I do not see where there is a moonlight IPA listed.
> > > > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> > > 
> > > 
> > > My IPA was built with the $99 a year license already attached
> > 
> > 
> > Would you be interested in forking and adding it to your Github? I believe it would be a popular addition to your repo if you choose to do that. I intended to do this same thing myself, but you guys beat me to it. Whatever you decide, thanks so much for the support from all of you that have helped. I'm very grateful to see others who feel the same way I do about this restriction from Apple. I feel really bad for Cameron who got put in this position by Apple.
> 
> forking this does not make sense as all I did was turn off a flag in build settings. also if I fork it you will still need to sign it yourself when you build it. I only signed those specific IPA files

Thank you for clarifying.

**Comment by boazvdwansem** [comment]
> > > > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > > > 
> > > > 
> > > > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > > > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > > > When going to your URL, I do not see where there is a moonlight IPA listed.
> > > > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> > > 
> > > 
> > > My IPA was built with the $99 a year license already attached
> > 
> > 
> > Would you be interested in forking and adding it to your Github? I believe it would be a popular addition to your repo if you choose to do that. I intended to do this same thing myself, but you guys beat me to it. Whatever you decide, thanks so much for the support from all of you that have helped. I'm very grateful to see others who feel the same way I do about this restriction from Apple. I feel really bad for Cameron who got put in this position by Apple.
> 
> forking this does not make sense as all I did was turn off a flag in build settings. also if I fork it you will still need to sign it yourself when you build it. I only signed those specific IPA files

It’s possible to use someone else’s certificate? I thought that to install it to my device I’d need to sign it myself.

**Comment by boazvdwansem** [comment]
> > > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > > 
> > > 
> > > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > > When going to your URL, I do not see where there is a moonlight IPA listed.
> > > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> > 
> > 
> > I tried connecting inside my LAN to WAN, that was the issue. The URL I posted is to add in a apt package manager if jailbroken (Cydia for example). The only way around the 7 days limitation that I know of is AltStore/ jailbreak. I have uploaded an IPA I built myself to: https://github.com/boazvdwansem/ios-repo/tree/main/ipas, but it should be t almost identical as the one @don17sch posted
> 
> Awesome, thanks for clarifying, and thanks for all the help. You guys are awesome.

All the credit goes to @cgutman, @abusse and @don17sch. All I did was rebuilt the IPA and post it for others to download. I also made a Reddit post which already has ~200 upvotes: https://www.reddit.com/r/jailbreak/comments/p0pxiu/free_release_moonlight_streaming_service_unlocked/?utm_source=share&utm_medium=ios_app&utm_name=iossmf.

**Comment by don17sch** [comment]
> 
> 
> > > > > > I have uploaded the file to my repo at https://boazvdwansem.github.io/ios-repo/ for anyone interested
> > > > > 
> > > > > 
> > > > > Thanks for plugging away at this, and just to confirm: You were trying to connect to your WAN IP from inside your LAN and that is why you said it did not work?
> > > > > In order to connect to your WAN IP, you need to be on the Internet (WAN).
> > > > > When going to your URL, I do not see where there is a moonlight IPA listed.
> > > > > Is the IPA you are hosting the same one that was provided by don17sch? I already downloaded his and so now my next question is, do you need to keep rebuilding this every 7 days? Or is there a way around that limitation without paying Apple $99/year?
> > > > 
> > > > 
> > > > My IPA was built with the $99 a year license already attached
> > > 
> > > 
> > > Would you be interested in forking and adding it to your Github? I believe it would be a popular addition to your repo if you choose to do that. I intended to do this same thing myself, but you guys beat me to it. Whatever you decide, thanks so much for the support from all of you that have helped. I'm very grateful to see others who feel the same way I do about this restriction from Apple. I feel really bad for Cameron who got put in this position by Apple.
> > 
> > 
> > forking this does not make sense as all I did was turn off a flag in build settings. also if I fork it you will still need to sign it yourself when you build it. I only signed those specific IPA files
> 
> It’s possible to use someone else’s certificate? I thought that to install it to my device I’d need to sign it myself.

I do not know the answer for sure. maybe @cgutman knows?

**Comment by Heath123** [comment]
You can use AltStore or a jailbreak to sideload without paying

**Comment by Mazztwo** [comment]
This worked like a charm! I develop mobile apps for a living, so I was able to remove ENABLE_APP_STORE_RESTRICTIONS by searching for it. I then ran 'git submodule update --init --recursive' like @don17sch suggested. Then I built the app and put it on my iPad. I disconnected my iPhone and iPad from wifi and then connected the iPad to my iPhones mobile hotspot. I am able to connect to my laptop over cellular :) 

THANK GOD for open source software. Also THANK YOU to @cgutman for everything, always <3

**Comment by U-siro** [comment]
I found a alternate method to bypass this limitation.
Use a IPv6 address: if your ip is 1.1.1.1 input ::ffff:1.1.1.1
Then it will added without any vpn.

https://www.ibm.com/docs/en/zos/2.4.0?topic=addresses-ipv4-mapped-ipv6

**Comment by cgutman** [comment]
> Why is this not allowed for moonlight but microsoft remote desktop can do it?

Section 4.2.7 of the [App Store Review Guidelines](https://developer.apple.com/app-store/review/guidelines/#design) states:

If your remote desktop app acts as a **mirror of specific software or services rather than a generic mirror of the host device**, it must comply with the following:

Emphasis mine.

**Comment by wangshuai-007** [comment]
I found,If I use ipv6 address,I can add my computer.
 `curl 6.ipw.cn` command can get my ipv6 address

**Comment by hwillson** [comment]
For anyone else landing here and looking for simplest way to enable Moonlight on iOS to stream from a remote (e.g. cloud) server, @U-siro's above [comment](https://github.com/moonlight-stream/moonlight-ios/issues/417#issuecomment-1001257949) is absolutely all that is needed. Just get your remote server's IP, e.g. `1.2.3.4`, then when you're adding a new host in the iOS Moonlight app, prefix the IP you enter with `::ffff:` - e.g. `::ffff:1.2.3.4`. That's it that's all - no need to build your own version of the client. I'm not sure which version of the Moonlight iOS client I'm using in case that matters, but I just downloaded whatever is the most recent version in the app store as of today.

**Comment by austinarchibald** [comment]
The `::ffff:` workaround works great, but it doesn't work with URLs (e.g. DNS services that give a static URL that matches your dynamic IP address). I have to delete and re-add the host every so often. Not a huge deal, but wondering if there's a better solution to that? Thanks.

**Comment by U-siro** [comment]
> The `::ffff:` workaround works great, but it doesn't work with URLs (e.g. DNS services that give a static URL that matches your dynamic IP address). I have to delete and re-add the host every so often. Not a huge deal, but wondering if there's a better solution to that? Thanks.

@austinarchibald Is it means your real IP is behind DNS? as I tried, DNS Hostname works without any problem or checking.

**Comment by austinarchibald** [comment]
> > The `::ffff:` workaround works great, but it doesn't work with URLs (e.g. DNS services that give a static URL that matches your dynamic IP address). I have to delete and re-add the host every so often. Not a huge deal, but wondering if there's a better solution to that? Thanks.
> 
> @austinarchibald Is it means your real IP is behind DNS? as I tried, DNS Hostname works without any problem or checking.

Correct, DNS hostname. Not working for me, and I've tried several cloud rigs I use, all with custom DNS hostnames. It says:

```
Add Host Manually
Could not connect to host. Ensure GameStream is enabled in GeForce Experience on your PC.
```

**Comment by Aarav5255** [comment]
> > > The `::ffff:` workaround works great, but it doesn't work with URLs (e.g. DNS services that give a static URL that matches your dynamic IP address). I have to delete and re-add the host every so often. Not a huge deal, but wondering if there's a better solution to that? Thanks.
> > 
> > 
> > @austinarchibald Is it means your real IP is behind DNS? as I tried, DNS Hostname works without any problem or checking.
> 
> Correct, DNS hostname. Not working for me, and I've tried several cloud rigs I use, all with custom DNS hostnames. Only works when I type the IP address. It says:
> 
> > Add Host Manually
> > Could not connect to host. Ensure GameStream is enabled in GeForce Experience on your PC.

same, have you found any solutions?

**Comment by austinarchibald** [comment]
The `::ffff:` workaround no longer works for me on tvOS. For some reason, my tvOS app showed no connection even though it does on all other clients, iPhone, Mac, Steam Deck, etc. So I removed host and tried to re-add, and I get the "enable GameStream" error. Tried rebooting the host. The host still works on my iPhone - I don't dare remove host and re-add to see if the workaround still works on iOS. Very strange. I don't want to have to set up a VPN.

**Comment by austinarchibald** [comment]
> I believe it is because of recent Moonlight client update on App Store. With the update non-default port support has been enabled for moonlight. Both IPv6 adresses and port separator are using ":" I think it is because of this change

Interesting, is there a way around this? If not, we need it switched back...

**Comment by bayramog** [comment]
> > I believe it is because of recent Moonlight client update on App Store. With the update non-default port support has been enabled for moonlight. Both IPv6 adresses and port separator are using ":" I think it is because of this change
> 
> Interesting, is there a way around this? If not, we need it switched back...

As far as I tried, I couldn't find a way around. I believe the app needs a new implementation to better understand the difference between IPv6 and IPv4 with a special port.

**Comment by cgutman** [comment]
IPv6 addresses now need to be enclosed in brackets (like in URLs) to allow the (optional) port to be distinguished from the IPv6 address itself.

**Comment by bayramog** [comment]
> IPv6 addresses now need to be enclosed in brackets (like in URLs) to allow the (optional) port to be distinguished from the IPv6 address itself.
> 
> 
> 
> Example: `[2001:db8::1]` or `[2001:db8::1]:47989`

This worked, thanks!

**Comment by Jun-WeiMao** [comment]
> > IPv6 addresses now need to be enclosed in brackets (like in URLs) to allow the (optional) port to be distinguished from the IPv6 address itself.
> > Example: `[2001:db8::1]` or `[2001:db8::1]:47989`
> 
> This worked, thanks!

I've been try a lot of format and not working...

Should full value formt be like ```::ffff:[2001:db8::1]:47989``` ? Can you provide an example, Thanks!

**Comment by FishOrBear** [comment]
You can use url to access your host, I discovered it by accident.
First of all, your device needs to be in the same local area network as your host, and then resolve the dns domain name to your wan ip. At this time, you can add the host normally, then you turn off your wifi, use the mobile network, restart moonlight, and you will You can connect to your host from the external network.

**Comment by Humpzinho** [comment]
> For anyone else landing here and looking for the simplest way to enable Moonlight on iOS to stream from a remote (e.g. cloud) server, @U-siro's above [comment](https://github.com/moonlight-stream/moonlight-ios/issues/417#issuecomment-1001257949) is absolutely all that is needed. Just get your remote server's IP, e.g. `1.2.3.4`, then when you're adding a new host in the iOS Moonlight app, prefix the IP you enter with `::ffff:` - e.g. `::ffff:1.2.3.4`. That's it that's all - no need to build your own version of the client. I'm not sure which version of the Moonlight iOS client I'm using in case that matters, but I just downloaded whatever is the most recent version in the app store as of today.

Hi, is it still working in 2023? Even with the lastest moonlight release and NVIDIA Drivers on my PC?

**Comment by Humpzinho** [comment]
> For anyone else landing here and looking for the simplest way to enable Moonlight on iOS to stream from a remote (e.g. cloud) server, @U-siro's above [comment](https://github.com/moonlight-stream/moonlight-ios/issues/417#issuecomment-1001257949) is absolutely all that is needed. Just get your remote server's IP, e.g. `1.2.3.4`, then when you're adding a new host in the iOS Moonlight app, prefix the IP you enter with `::ffff:` - e.g. `::ffff:1.2.3.4`. That's it that's all - no need to build your own version of the client. I'm not sure which version of the Moonlight iOS client I'm using in case that matters, but I just downloaded whatever is the most recent version in the app store as of today.

Hi, is it still working?

**Comment by Epoch2022-iOS** [comment]
> 我找到了一种替代方法来绕过这个限制。使用IPv6地址：如果您的ip是1.1.1.1输入::ffff:1.1.1.1然后它将在没有任何vpn的情况下添加。
> 
> [https://www.ibm.com/docs/en/zos/2.4.0?主题=地址-ipv4-mapped-ipv6](https://www.ibm.com/docs/en/zos/2.4.0?topic=addresses-ipv4-mapped-ipv6)

hello, if I use ipv6, Does this mean that my remote computer needs to support ipv6？

**Comment by Epoch2022-iOS** [comment]
> IPv6地址现在需要用括号括起来（如URL），以便将（可选）端口与IPv6地址本身区分开来。
> 
> 示例：`[2001:db8::1]`或`[2001:db8::1]:47989`

hello，If my remote server uses a port other than the default 47989, how do I modify the port information

**Comment by Epoch2022-iOS** [comment]
> > 对于任何在这里登陆并寻找启用iOS上的Moonlight从远程（例如云）服务器进行流式传输的最简单方法的人来说，@U-siro的上述[评论](https://github.com/moonlight-stream/moonlight-ios/issues/417#issuecomment-1001257949)绝对是全部需要的。只需获取远程服务器的IP，例如`1.2.3.4`，然后当您在iOS Moonlight应用程序中添加新主机时，将您输入的IP作为前缀`::ffff:`-例如`::ffff:1.2.3.4`。仅此而已-无需构建自己的客户端版本。我不确定我使用的是哪个版本的Moonlight iOS客户端，以防这很重要，但截至今天，我刚刚在应用程序商店下载了最新版本。
> 
> 嗨，它还在工作吗？

hey, if you get the answer, pls share it!

**Comment by pkpgdjk** [comment]
It still works. I just tried today. but I have to use `[ ]` . For example, my server IP is 13.123.3.132. I use `::ffff:13.123.3.132` I got an error, but when I use `[::ffff:13.123.3.132]` it works fine.

**Comment by Epoch2022-iOS** [comment]
> It still works. I just tried today. but I have to use `[ ]` . For example, my server IP is 13.123.3.132. I use `::ffff:13.123.3.132` I got an error, but when I use `[::ffff:13.123.3.132]` it works fine.

thanks bro! This is very important to me. by the way, One more question, does this method only support ipv6 addresses?

**Comment by Epoch2022-iOS** [comment]
> sry, can you give me more info about your question. if my understand is correct the server listening at ipv4, but we can pass the ipv4 in the format of ipv6 by using `::ffff:IPV4`. So, the moonlight application can be bypassed by the method above . But I don't know we have to enable ipv6 for internet router or the target server or not.

thanks! my IPV4 address is 116.21.86.170,I input the [::ffff:116.21.86.170] when add the pc. but it does not work well, I get the `Your device's network connection is blocking Moonlight. Streaming may not work while connected to this network` error tips, It is worth noting that I used a custom port (36012) instead of the default port. pls help me....it's bad exp. for me.

**Comment by pkpgdjk** [comment]
have you try `[::ffff:116.21.86.170]:36012`

**Comment by Epoch2022-iOS** [comment]
> have you try `[::ffff:116.21.86.170]:36012`

thanks!!!! dear!!! it's work!

**Comment by Steinheausser** [comment]
Hello, just wanted to leave this here in case anybody else is as dumb as me trying to get this working. If you are using sunshine and moonlight's ios client, ensure that you have UPNP on sunlight enabled, and that you are on version 0.20 of sunlight, and that you follow the sunshine 0.20 instructions on uninstalling moonlight hosting services. These three things in tandem with passing through the ip via ipv6 as discussed removed my need for zerotier (which while performant, was unstable in random connection terminations on ios) hopefully it might work for you. Thanks to all in the discussion up to this point.

**Comment by Epoch2022-iOS** [comment]
> Hello, just wanted to leave this here in case anybody else is as dumb as me trying to get this working. If you are using sunshine and moonlight's ios client, ensure that you 1. have UPNP on sunlight enabled; 2. are on version 0.20 of sunlight; 3. follow the sunshine 0.20 instructions on uninstalling moonlight hosting services. These three things in tandem with passing through the ip via ipv6 as discussed removed my need for zerotier (which while performant, was unstable in random connection terminations on ios) hopefully it might work for you. I was previously having request timed out when I managed to connect to the PC. Thanks to all in the discussion up to this point.

thanks！I've fixed the issue and now I can connect to my remote PC via my iOS device

**Comment by Jk541957** [comment]
I know I’m about 2 years late on this but any chance someone can share the IPA again with the restriction removed?

**Comment by hwillson** [comment]
@Jk541957 you shouldn't need it; just use the `[::ffff:1.2.3.4]` (where `1.2.3.4` if your IP) approach discussed in the last several comments of this thread.

**Comment by RainySat** [comment]
Try this method. First, add it using the internal IP address within the local network. Once the connection is successful, switch to the cellular network without deleting the existing Host entry, and add it again, this time using the URL. It will prompt an update success message. Now you can directly connect from the external network.

**Comment by jakealsko** [comment]
> Hello, just wanted to leave this here in case anybody else is as dumb as me trying to get this working. If you are using sunshine and moonlight's ios client, ensure that you 1. have UPNP on sunlight enabled; 2. are on version 0.20 of sunlight; 3. follow the sunshine 0.20 instructions on uninstalling moonlight hosting services. These three things in tandem with passing through the ip via ipv6 as discussed removed my need for zerotier (which while performant, was unstable in random connection terminations on ios) hopefully it might work for you. I was previously having request timed out when I managed to connect to the PC. Thanks to all in the discussion up to this point.

I did all of these things and I still get "Could not connect to host." What am I doing wrong?

**Comment by GabrielNezovic** [comment]
Thanks to [U-siro](https://github.com/moonlight-stream/moonlight-ios/issues/417#issuecomment-1001257949)'s suggestion, this IPv6 work-around is working perfectly for me using the following steps -

- Ensure both the Host Gaming PC and iOS device are on the same Local Network.
- Ensure that the following Network Ports are forwarded in any Routers and Firewalls along the network stream
```
TCP 47984, 47989, 48010
UDP 47998, 47999, 48000, 48002, 48010
```

1. Open the iOS App and select "Add Host Manually"
2. Enter the local IP address of your Host Gaming PC (eg, 192.168.1.5) and tap OK.
3. A pop-up message should be displayed on both the iOS App and the Host Gaming PC - enter the security code into the Host Gaming PC to validate the connection
4. Close the iOS App from the App Switcher
5. Open the iOS App again and select "Add Host Manually"
6. Enter ::ffff: followed by the [Public IP Adress](https://www.whatismyip.com/) of the Host Gaming PC, eg
`::ffff:123.456.789.000`
7. If all goes well, another pop-up message will be displayed in the iOS App to say  "Host Successfully Updated".

That's it! 
You should now be able to connect to your Host Gaming PC remotely.

**Comment by predprey2** [comment]
Has something changed recently with local network privacy in iOS 17? Not sure when it started, but on iOS 17 iPhone 14, Moonlight stopped discovering devices on local network.

**Comment by Madmegsox1** [comment]
I think WAN connections will be allowed in iOS17.4 due to the EU regulations. Is there a possibility that this could be looked at into?

**Comment by Vladoker** [comment]
It only worked for me with the addition of square brackets [::ffff:1.2.3.4] and some settings of the sunshine network

**Comment by BitGrub** [comment]
I had it working until very recently. Not sure what changed, but I can no longer connect remotely via ddns on iPhone
