### ISSUE TITLE
Mouse speed too sensitive in iOS 14

### ISSUE THREAD

**Issue by don17sch** [moonlight-stream/moonlight-ios#421]
several of us on Discord have noticed that the mouse speed is too sensitive in iOS 14 when using Magic Keyboard, Magic Mouse 2, or the Logitech Folio trackpad. The mouse is moving to fast and is not able to be precise. The current fix is to change mouse speed in both iOS as well as the remote server. This is only a temp fix as it resets back to highly sensitive. 
This issue is inconsistent and does not happen every single time.

**Comment by zaptrem** [comment]
This isn't a mouse-specific issue, it is present on every mouse I've tested (two Razor mice, one MS mouse, two Smart Connector trackpads). It also isn't always too sensitive, but the cause of the switch over to hyper-speed mode isn't known. Worse than the swings in sensitivity is the accompanying fact that precision drops through the floor. One "dot" of recognized movement by the mouse/iOS translates to several pixels on the guest, even when sensitivity is cranked down on both ends.

**Comment by DoctorWhoof** [comment]
Confirming on iPad Pro with Magic Keyboard. When using the touch screen, there’s a near perfect 1:1 movement on the remote mouse cursor, but moving the cursor with the Magic Keyboard trackpad results in super fast mouse movement.

**Comment by zaptrem** [comment]
@DoctorWhoof Does it seem normal on app launch? Mine only seems to start going crazy when I open multitasking.

**Comment by DoctorWhoof** [comment]
@zaptrem Interesting! I tried again (hard booted the remote machine) and... it's fine now.

Don't know what led to the problem here in the first place, will post if I can repro. When you say multitasking, do you mean specifically alt+tab switching, or just working in many things at once in general? I briefly using other open windows and so far no problem.

Thanks!

**Comment by zaptrem** [comment]
iOS multitasking. Either way, the sensitivity seems so far off from Windows it's hard to play games.

**Comment by DoctorWhoof** [comment]
Ah yes. Confirmed. Every time I switch away to another app in iOS and come back, the trackpad-to-mouse speed gets faster and faster in Moonlight, as if it's getting multiplied by some value, until it gets unusable.

Running the latest iOS Moonlight and Windows 10 Pro 18363.1082 on remote machine.

**Comment by cgutman** [comment]
The problem is that iOS 14 is reporting the same mouse deltas multiple times.

```
2020-10-11 16:58:16.481615-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-16.000000, -6.000000)
2020-10-11 16:58:16.481917-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-16.000000, -6.000000)
2020-10-11 16:58:16.482084-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-16.000000, -6.000000)
2020-10-11 16:58:16.497942-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-20.000000, -10.000000)
2020-10-11 16:58:16.498247-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-20.000000, -10.000000)
2020-10-11 16:58:16.498415-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-20.000000, -10.000000)
2020-10-11 16:58:16.514269-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-23.000000, -13.000000)
2020-10-11 16:58:16.514576-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-23.000000, -13.000000)
2020-10-11 16:58:16.514744-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-23.000000, -13.000000)
2020-10-11 16:58:16.529844-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-23.000000, -14.000000)
2020-10-11 16:58:16.530085-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-23.000000, -14.000000)
2020-10-11 16:58:16.530199-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-23.000000, -14.000000)
2020-10-11 16:58:16.545514-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-24.000000, -14.000000)
2020-10-11 16:58:16.545734-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-24.000000, -14.000000)
2020-10-11 16:58:16.545818-0500 GCMouseTest[1813:1232317] Mouse 0x100a09ca0 moving by (-24.000000, -14.000000)```

I'm putting together a sample app to demonstrate the issue for Apple.

**Comment by cgutman** [comment]
I filed an issue with Apple in the Feedback Assistant with a sample project. I will update this issue as Apple provides updates on my feedback report.

Attached is the sample project I provided to Apple if you would like to play with it.
[GCMouseTest.zip](https://github.com/moonlight-stream/moonlight-ios/files/5362319/GCMouseTest.zip)

**Comment by zaptrem** [comment]
Part of this issue is Nvidia Game Stream messing with the Windows mouse sensitivity settings every time you resume a stream (even when using the mouse sensitivity fix script on the Discord server). Restarting the app every time you tab out of Moonlight and verifying the Windows sensitivity settings when you get back in seems to result in a reliable sensitivity (though one that doesn’t quite match the same mouse plugged into the machine natively, but that’s a different issue).

**Comment by cgutman** [comment]
I believe this is fixed in iOS 14.2 beta 3. I don't have physical hardware to test but the repro I had in the emulator is gone now.

It may also be fixed in iOS 14.1 GM as this SDL commit states https://hg.libsdl.org/SDL/rev/b7f667be5260

**Comment by zaptrem** [comment]
@cgutman Issue is resolved in iPadOS 14.2 beta 3 on an iPad Pro gen 3. However, the stream instantly ends after switching to another app and switching back (no matter how fast).

**Comment by cgutman** [comment]
Thanks for confirming. Apple also updated the feedback request:
<img width="901" alt="Screen Shot 2020-10-18 at 5 13 16 PM" src="https://user-images.githubusercontent.com/2695644/96387090-4ca23500-1165-11eb-9094-485d2cbedb24.png">

I don't think it was ever guaranteed by the OS that the app won't be backgrounded on switching apps. Once we get the `applicationDidEnterBackground` callback, we _have_ to stop streaming. We will be suspended and won't be able to communicate with the host even if we wanted to.

**Comment by zaptrem** [comment]
@cgutman No problem. Could the app instead save state (PC/game last connected to) on applicationDidEnterBackground and restore (“resume stream”) that on the callback for returning from background?

**Comment by cgutman** [comment]
The bug is still present in 14.1, so we will indeed have to wait until 14.2 for a resolution.

@zaptrem we can discuss more on Discord. This isn't related to the bug reported here.

**Comment by cgutman** [comment]
Fixed in iOS 14.2
