### ISSUE TITLE
Connection Interrupted.The client is not authorized.Certificate verification failed.

### ISSUE THREAD

**Issue by VoxHwa** [moonlight-stream/moonlight-ios#485]
**Screenshots**
![pairing](https://user-images.githubusercontent.com/96711835/150717224-9e8ebe05-4b40-4f8c-9167-d1d6a65d49c8.jpg)

- It occured just after I correctly entered the pairing code on my gaming pc,but my iphone showed this.
- And proabably a lot of people have encountered this issue,for I've seen many talked about it, but nobody answered or solved.

**Other Moonlight clients**
- If I used another pc to stream the gaming pc,moonlight client won't show anything after I entered the pairing code.

 I've tried many ways that I think might have sth to do with this issue,but all not working.

My gaming pc Geforce Expericence is the latest version,(which I have reinstalled),shield is working,all ports are allowed to pass.

Plus:my router is using WiFi 6

**Device details (please complete the following information)**
 - iOS/tvOS version: [iOS 14.6]
 - Device model: [ iPhone 11 Pro]

**Server PC details (please complete the following information)**
 - OS: [Windows 10 20H2]
 - GeForce Experience version: [3.24.0.126]
 - Nvidia GPU driver: [511.23]
 - Antivirus and firewall software: [Windows Defender and Windows Firewall](I've uninstalled McAfee,but proved not criminal)

**Additional context**
I guess It has sth to do with nv driver or geforce experience shield client authorization strategy.

**Comment by cgutman** [comment]
Does it happen consistently each time you try to pair?

**Comment by VoxHwa** [comment]
> Does it happen consistently each time you try to pair?

Yes,every time.😢

**Comment by cgutman** [comment]
Since you experience a similar issue with the Moonlight PC client, please run that, try to pair, and collect logs. They will be in the `%TEMP%` folder on Windows and named `Moonlight-###.log`

**Comment by VoxHwa** [comment]
[Moonlight-1643008878.log](https://github.com/moonlight-stream/moonlight-ios/files/7923528/Moonlight-1643008878.log)
The log is generated from my pc connecting to my pc via moonlight(I think it's similar)

**Comment by VoxHwa** [comment]
I borrowed a macbook to test.The same happened again.But I noticed that the streaming host pc showed geforce experience tip sometimes(Press Alt+Z to use geforce experience in the game)

**Comment by VoxHwa** [comment]
I just updated the nvidia driver,which is the latest version.
No help.

**Comment by Howard20181** [comment]
Downgrading GeForce Experience to `3.21.0.36` will allow successful pairing, and then updating to a new version will cause the pairing to loop.

**Comment by VoxHwa** [comment]
> Downgrading GeForce Experience to `3.21.0.36` will allow successful pairing, and then updating to a new version will cause the pairing to loop.

Geforce Experience version where to downgrade?
Plus,so is no relation with driver version?
Thanks

**Comment by VoxHwa** [comment]
Downgrade geforce version works!

**Comment by Howard20181** [comment]
> Plus,so is no relation with driver version?

Yes

**Comment by VoxHwa** [comment]
> > Plus,so is no relation with driver version?
> 
> Yes

thanks again.

**Comment by FrenchRedPaw** [comment]
I downgrading GeForce Experience to 3.21.0.36 and did not have "Open in-game overlay"
Repair moonlight and start searching my PC (Found nothing) 
Included GFE and he start to update 3.23
Start searching my PC (Found nothing) 
I am from another country and may not understand the meaning of your actions. Excuse me for my stupidity.

**Comment by Howard20181** [comment]
> I downgrading GeForce Experience to 3.21.0.36 and did not have "Open in-game overlay"
> Repair moonlight and start searching my PC (Found nothing) 
> Included GFE and he start to update 3.23
> Start searching my PC (Found nothing) 
> I am from another country and may not understand the meaning of your actions. Excuse me for my stupidity.

1. Downgrade GFE to 3.21
2. Enter your computer's IP in Moonlight and pair it
3. Upgrade GFE (optional)

**Comment by FrenchRedPaw** [comment]
> > I downgrading GeForce Experience to 3.21.0.36 and did not have "Open in-game overlay"
> > Repair moonlight and start searching my PC (Found nothing)
> > Included GFE and he start to update 3.23
> > Start searching my PC (Found nothing)
> > I am from another country and may not understand the meaning of your actions. Excuse me for my stupidity.
> 
> 1. Downgrade GFE to 3.21
> 2. Enter your computer's IP in Moonlight and pair it
> 3. Upgrade GFE (optional)

"Unable to connect to the specified PC"

**Comment by VoxHwa** [comment]
> > > I downgrading GeForce Experience to 3.21.0.36 and did not have "Open in-game overlay"
> > > Repair moonlight and start searching my PC (Found nothing)
> > > Included GFE and he start to update 3.23
> > > Start searching my PC (Found nothing)
> > > I am from another country and may not understand the meaning of your actions. Excuse me for my stupidity.
> > 
> > 
> > 
> > 1. Downgrade GFE to 3.21
> > 2. Enter your computer's IP in Moonlight and pair it
> > 3. Upgrade GFE (optional)
> 
> "Unable to connect to the specified PC"

May better check your local network and firewall settings.

**Comment by FrenchRedPaw** [comment]
> > > > I downgrading GeForce Experience to 3.21.0.36 and did not have "Open in-game overlay"
> > > > Repair moonlight and start searching my PC (Found nothing)
> > > > Included GFE and he start to update 3.23
> > > > Start searching my PC (Found nothing)
> > > > I am from another country and may not understand the meaning of your actions. Excuse me for my stupidity.
> > > 
> > > 
> > > 
> > > 1. Downgrade GFE to 3.21
> > > 2. Enter your computer's IP in Moonlight and pair it
> > > 3. Upgrade GFE (optional)
> > 
> > 
> > "Unable to connect to the specified PC"
> 
> May better check your local network and firewall settings.

My GFE just update to 3.25.0.84 and Moonlight working 
Lmao 
But thanks for your support and responsiveness :D

**Comment by cgutman** [comment]
Closing this out as it was a GFE issue fixed in 3.25.0.84.

> Fixed an issue with Gamestream with pin pairing.

https://www.nvidia.com/en-us/geforce/geforce-experience/download/

**Comment by Howard20181** [comment]
> Closing this out as it was a GFE issue fixed in 3.25.0.84.

After updating to the new version I still can't pair.

**Comment by Howard20181** [comment]
[nvstreamsvc.log](https://github.com/moonlight-stream/moonlight-ios/files/8054890/nvstreamsvc.log)

https://user-images.githubusercontent.com/40033067/153736820-18b0bfc6-1d3a-4489-97d0-fce3915cd5c0.mp4

**Comment by zhfish** [comment]
> > Closing this out as it was a GFE issue fixed in 3.25.0.84.
> 
> After updating to the new version I still can't pair.

me too

**Comment by frprm** [comment]
This issue is not resolved, the same problem still occurs with GFE 3.25.1.27.

**Comment by cgutman** [comment]
Possible duplicate of https://github.com/moonlight-stream/moonlight-android/issues/1056

Do you also have non-Latin characters in your username?

**Comment by frprm** [comment]
Yes, that is right! After following [these instructions](https://www.minitool.com/news/change-user-folder-name-windows-10.html) to rename my user account **and** user folder, the pairing now works.

**Comment by Howard20181** [comment]
Confirmed duplicate with https://github.com/moonlight-stream/moonlight-android/issues/1056
In my case, the inclusion of Chinese characters in the username causes this problem

**Comment by AetherKing** [comment]
> Yes, that is right! After following [these instructions](https://www.minitool.com/news/change-user-folder-name-windows-10.html) to rename my user account **and** user folder, the pairing now works.

Thank you very much! @frprm , this worked for me flawlessly with the current version of GFE 3.27.0.120 (as of Dec 4th, 2023), I had an Spanish accent in the Windows username, which was causing the "PC not paired" error, but this workaround worked perfectly! Cheers!
